name: cpmolgan
channels:
  - conda-forge
  - rdkit
  - defaults
dependencies:
  - python=3.6.10
  - pip=20.1.1
  - numpy=1.19.5
  - scikit-learn=0.24.2
  - pandas=1.1.5
  - tqdm=4.62.2
  - rdkit=2018.09.1
  - notebook=6.0.3
  - pip:
      - tensorflow-gpu==1.15.0
      - selfies==1.0.4